### PR TITLE
Move tx version 3 and remove timestamp

### PR DESCRIPTION
**Pull request by captainbuckkets**
Please review and let me know if anything else needs to change. 

See for tx proof: https://tblockbook.peercoin.net/tx/aa4e18180504fbd61c4eb788b672bee837b0c660b19b22bd9464ea758925bea9

### CODE REVIEW

**Comment by backpacker69** [comment]
this merge request breaks signing of v2 txns

**Comment by captainbuckkets** [comment]
Both of these were signed and accepted.  Not sure how to form a v2 tx to test it or what the difference from v1 would be

v3: 4ce1bc624a79061990378815db5b323b09ae7c6dbb46f9701e1e77b684f6dacf
v1: bf9b367998422104670644789f18e858803f3bae0043b593419df30425e03cd1

**Review by backpacker69 — CHANGES_REQUESTED** [review]
it's very messy, please remove logging and empty lines and change of whitespace.

**Review by captainbuckkets — COMMENTED** [review]
I believe I have corrected and removed the whitespaces/logging.

**Review by backpacker69 — APPROVED** [review]

**Pull request merged**
